### PR TITLE
resolves #29 update c3.js defaults to latest version 0.7.20

### LINKED ISSUE #29: Upgrade c3.js to the latest version
The latest version is 0.7.20 while we are still using 0.3.0: https://github.com/c3js/c3/releases/tag/v0.7.20

### PR DESCRIPTION
**Pull request by uniqueck**
fixes #29

### CODE REVIEW

**Comment by Mogztter** [comment]
Did you make sure that everything works as expected? It's surprising that there's not a single breaking change?

**Comment by uniqueck** [comment]
How? Should I use this gem and render some example files and check if this chart looks ok?

**Comment by Mogztter** [comment]
Yes, we can add a few examples in this repository to make it easier to test when we upgrade.
We could potentially use something like Cypress to automate things but one step at a time 😉

**Comment by uniqueck** [comment]
How do you generate those example graphics? Do you install this gem and you this to generate these png / svg?

**Comment by Mogztter** [comment]
> How do you generate those example graphics?

Are you referring to the screenshots in the README?
I created an AsciiDoc file, converted it to HTML with this extension enabled and then took screenshots.
Technically, we could automate the process using Puppeteer but I don't know if it's worth it.

**Comment by uniqueck** [comment]
My question was more aimed at how to use my local packaged Ruby Gem to generate these previews?

**Comment by Mogztter** [comment]
I believe the easiest way is to require `lib/asciidoctor-chart.rb` from your local copy:

```
asciidoctor -r ./lib/asciidoctor-chart.rb doc.adoc
```

**Comment by uniqueck** [comment]
Do you know a way to call npm from bundle exec? I would like to use cypress for visual regression tests and the cypress gem for ruby is for rails.

**Comment by Mogztter** [comment]
I don't mind adding a `package.json` (since we want to transpile this extension to JavaScript). You can call `npm` directly and use Cypress from Node.

**Comment by Mogztter** [comment]
However, please create a dedicated issue and pull request to introduce this change.

**Comment by uniqueck** [comment]
> However, please create a dedicated issue and pull request to introduce this change.

Yes that was my plan, but i would like to try it and investigate for a solution, to check if all is fine after upgrade to latest version of c3.js.

**Comment by uniqueck** [comment]
I created another issue #33 for that, i think it is a good idea to wait with this change for a solution of #33.

**Comment by uniqueck** [comment]
Should rebased and merged after #34.

**Comment by Mogztter** [comment]
The rendering slightly changed but it's barely noticeable:
### After

image

Margin between 0 and 1 at the bottom is thinner and the graph is slightly wider.

### Before

image

**Comment by Mogztter** [comment]
Rebased on master and base image for C3.js updated

**Pull request merged**
